#!/usr/bin/env python3
"""Copy shared/jev-brain.json to every client that embeds it.

  python3 tools/sync_brain.py          write the copies
  python3 tools/sync_brain.py --check  exit 1 if any copy is stale

A client whose directory does not exist yet is skipped.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "shared" / "jev-brain.json"


def targets(text):
    swift = (
        "// Generated by tools/sync_brain.py from shared/jev-brain.json. Do not edit.\n"
        'let brainJSONText = #"""\n' + text.rstrip("\n") + '\n"""#\n'
    )
    return {
        ROOT / "extension" / "brain.json": text,
        ROOT / "mac" / "Sources" / "JevCore" / "Brain.generated.swift": swift,
    }


def main(argv):
    text = SRC.read_text(encoding="utf-8")
    stale = []
    for path, content in targets(text).items():
        if not path.parent.exists():
            continue
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if "--check" in argv:
            stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("stale (run tools/sync_brain.py): " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
